import { PrinterIcon, ShoppingBagIcon, ShoppingCartIcon } from "@heroicons/react/24/outline";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="bg-white min-h-screen">
      <Head>
        <title>Smart-stock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center h-screen ">
        <h1 className="text-4xl font-bold text-indigo-600">Bienvenu chez nous</h1>
        <p className="text-xl text-slate-600 py-5">Fonctionnalite present et avenir</p>
        <div className="flex space-x-4">
          <Link href="/products">
            <div className="h-24 flex flex-col justify-center cursor-pointer px-6 items-center flex-1 border border-blue-500 rounded-md bg-blue-500 text-white">
              <ShoppingBagIcon className="h-5 w-5" />
              <h2>Gestion de stock</h2>
            </div>
          </Link>
          <Link href="/">
            <div className="h-24 flex flex-col justify-center w-96 items-center flex-1 border border-orange-500 rounded-md bg-orange-500 text-white">
              <PrinterIcon className="h-5 w-5" />
              <h2>Gestion de rapports</h2>
            </div>
          </Link>
          <Link href="/ventes">
            <div className="h-24 flex flex-col justify-center cursor-pointer px-6 items-center flex-1 border border-purple-800 rounded-md bg-purple-500 text-white">
              <ShoppingCartIcon className="h-5 w-5" />
              <h2>Gestion de vente</h2>

            </div>
          </Link>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
